services:
  - type: web
    name: teach-competing-api
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.fast_api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teach-competing-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: teach-competing-db
    databaseName: teach_competing
    user: teach_user
    region: oregon