searcher:
  description: >
    1.使用'ChromaDB 语义检索工具'工具找出与 {topic} 有关的论文知识
    2.进行阅读找出其中最有洞见力的部分，根据不同的层级进行不同的思考策略：
      如果是层级 1，进行总结为简短的几句话，并将该总结后的内容标记为{简介}；
      如果是层级 2，仔细阅读该部分，找出核心论点，并标记为{论点}；
      如果是层级 3，同样尝试仔细阅读，找出其核心论点，并标记为{论点}；
    3.重复上述步骤，根据已知的{论点}思考关键词，使用检索工具进行相关查询，直到你找齐了3个足够新颖且前沿有科研价值的{论点}。
  expected_output: >
    输出3个关于 {topic} 最前沿的最有洞见力的{论点}与其相关的{简介}。
  agent: searcher

idea_thinker:
  description: >
    1.根据得到的3个{论点}结合{简介}与**你自己的知识（请结合你自己的知识）进行思考，有哪些地方可以创新
    2.在此基础上思考出我们论文的三个核心创新点，同时需给出创新的理由，记为{创新点1}、{理由1}，{创新点2}、{理由2}，{创新点3}、{理由3}
    3.对三个核心创新点分别进行一段阐述，记为{阐述1}，{阐述2}，{阐述3}
  expected_output: >
    对应的{论点}、{阐述}、{理由}为一组，依次输出三组创新点与阐述、理由
  agent: idea_thinker

writer1:
  description: >
    查看创新点与阐述，根据得到的三对创新点与阐述，完成正文部分论文大纲，直到作者满意。
    按照如下步骤进行正文部分论文大纲创作：
    1.结合{创新点}给出{论文大纲}的几个一级标题
    2.结合{创新点}、{阐述}、{理由}为每个一级标题下添加二级标题
    3.输出完整的{正文部分论文大纲}，询问作者是否满意，若作者不满意，则按照作者要求重新修改大纲。
  expected_output: >
    输出完整的{正文部分论文大纲}
  agent: writer1

writer2:
  description: >
    查看论文大纲，结合**你自己的知识（请结合自己的知识）完成一篇论文，现在需要你先写一篇论文来作为初稿。
    按照如下步骤进行书写：
    1.结合{论点}、{创新点}、与{简介}书写本文的摘要、关键词、引言三个部分。
    2.结合三个{创新点}、{阐述}、{理由}填充{正文部分论文大纲}。
    3.根据之前的内容思考，书写 总结与讨论 部分。
  expected_output: >
    一篇结构完整的论文
  agent: writer2

polisher:
  description: >
    请依据以下策略对文章进行系统性修改润色：
    – 调整句子结构和长度，增加表达的丰富度与变化感
    – 加入智性的犹豫表述（例如“可能表明”“似乎”“很可能”）
    – 在适当处补充细微差别、含蓄的批评或不同视角
    – 避免使用AI常见的陈词滥调词汇（如“深入探讨”“稳健的”“创新的”等）
    – 使用更自然的过渡（减少“因此”“此外”“综上所述”这类高频连接词）
    – 用具体、易引发共鸣或贴近现实的细节替换模糊案例
    – 调整语气风格，使其不那么刻板精致，更显真实（稍显随意也无妨）
    – 若相关，可融入第一人称叙述或轻松的轶事感
    – 打破句子开头的重复模式（例如避免每句话都以“本研究…”或“重要的是…”开头）
    – 保留核心原意和上下文，但提升自然度与真实感
  expected_output: >
    按照上述要求润色后的论文
  agent: polisher